version: '3.3'
services:
  mongo1:
    image: mongo
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    networks:
      - mongo-net
    expose:
      - 27017
  mongo2:
    image: mongo
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27018:27017
    networks:
      - mongo-net
    expose:
      - 27017
  mongo3:
    image: mongo
    command: --replSet rs0 --bind_ip_all
    ports:
      - 27019:27017
    networks:
      - mongo-net
    expose:
      - 27017

networks:
  mongo-net:
    driver: bridge
