version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
