version: '3.3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - redis-net

  express:
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - 3000:3000
    networks:
      - redis-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://localhost:6379

networks:
  redis-net:
    driver: bridge
